import { defineConfig, globalIgnores } from "eslint/config";
import js from "@eslint/js";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier/flat";
import tseslint from "typescript-eslint";

const eslintConfig = defineConfig([
  js.configs.recommended,
  ...nextVitals,
  ...nextTs,
  {
    linterOptions: { reportUnusedDisableDirectives: "error" },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { ignoreRestSiblings: true },
      ],
      eqeqeq: ["error", "always", { null: "ignore" }],
      "no-duplicate-imports": ["error", { allowSeparateTypeImports: true }],
      "no-var": "error",
      "prefer-const": "error",
    },
  },
  {
    files: ["src/**/*.{ts,tsx,mjs}"],
    // Integration-style unit tests may exercise both sides of a boundary.
    // Production imports and every other lint rule remain enforced.
    ignores: ["**/*.test.ts"],
    rules: {
      "import/no-cycle": ["error", { ignoreExternal: true }],
      "import/no-restricted-paths": [
        "error",
        {
          basePath: import.meta.dirname,
          zones: [
            {
              target: ["./src/lib", "./src/components", "./src/hooks"],
              from: ["./src/server", "./src/db"],
              message:
                "Keep server implementation out of shared/client modules. Shared contracts belong in src/lib.",
            },
            {
              target: ["./src/lib", "./src/server", "./src/db"],
              from: ["./src/components", "./src/hooks", "./src/app"],
              message:
                "Routes and UI compose domain and server modules; dependencies must not point back to presentation.",
            },
          ],
        },
      ],
    },
  },
  {
    files: ["**/*.{ts,tsx,mts,cts}"],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/await-thenable": "error",
      "@typescript-eslint/no-floating-promises": [
        "error",
        {
          // node:test owns the completion of registered tests. Promises inside
          // each test still require awaiting or explicit handling.
          allowForKnownSafeCalls: [
            { from: "package", package: "node:test", name: "test" },
          ],
        },
      ],
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/no-unnecessary-type-assertion": "error",
      "@typescript-eslint/switch-exhaustiveness-check": "error",
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { fixStyle: "inline-type-imports" },
      ],
    },
  },
  prettier,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Copied third-party bundles, generated by scripts/prepare-monaco.mjs.
    "public/monaco/**",
    "coverage/**",
    ".vercel/**",
    ".husky/_/**",
  ]),
]);

export default eslintConfig;
